/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StartRouteImport } from './routes/start'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InquiryDepositRouteImport } from './routes/inquiry.deposit'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as InquiryDepositReturnRouteImport } from './routes/inquiry.deposit.return'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryDepositRoute = InquiryDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => InquiryRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const InquiryDepositReturnRoute = InquiryDepositReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => InquiryDepositRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/builder': typeof BuilderRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/inquiry': typeof InquiryRouteWithChildren
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/support': typeof SupportRoute
  '/workspace': typeof WorkspaceRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/inquiry/deposit': typeof InquiryDepositRouteWithChildren
  '/inquiry/deposit/return': typeof InquiryDepositReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/builder': typeof BuilderRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/inquiry': typeof InquiryRouteWithChildren
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/support': typeof SupportRoute
  '/workspace': typeof WorkspaceRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/inquiry/deposit': typeof InquiryDepositRouteWithChildren
  '/inquiry/deposit/return': typeof InquiryDepositReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/builder': typeof BuilderRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/inquiry': typeof InquiryRouteWithChildren
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/support': typeof SupportRoute
  '/workspace': typeof WorkspaceRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/inquiry/deposit': typeof InquiryDepositRouteWithChildren
  '/inquiry/deposit/return': typeof InquiryDepositReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/builder'
    | '/checkout'
    | '/dashboard'
    | '/inquiry'
    | '/preview'
    | '/pricing'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/start'
    | '/support'
    | '/workspace'
    | '/checkout/return'
    | '/inquiry/deposit'
    | '/inquiry/deposit/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/builder'
    | '/checkout'
    | '/dashboard'
    | '/inquiry'
    | '/preview'
    | '/pricing'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/start'
    | '/support'
    | '/workspace'
    | '/checkout/return'
    | '/inquiry/deposit'
    | '/inquiry/deposit/return'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/builder'
    | '/checkout'
    | '/dashboard'
    | '/inquiry'
    | '/preview'
    | '/pricing'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/start'
    | '/support'
    | '/workspace'
    | '/checkout/return'
    | '/inquiry/deposit'
    | '/inquiry/deposit/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  BuilderRoute: typeof BuilderRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  InquiryRoute: typeof InquiryRouteWithChildren
  PreviewRoute: typeof PreviewRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  StartRoute: typeof StartRoute
  SupportRoute: typeof SupportRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry/deposit': {
      id: '/inquiry/deposit'
      path: '/deposit'
      fullPath: '/inquiry/deposit'
      preLoaderRoute: typeof InquiryDepositRouteImport
      parentRoute: typeof InquiryRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/inquiry/deposit/return': {
      id: '/inquiry/deposit/return'
      path: '/return'
      fullPath: '/inquiry/deposit/return'
      preLoaderRoute: typeof InquiryDepositReturnRouteImport
      parentRoute: typeof InquiryDepositRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface InquiryDepositRouteChildren {
  InquiryDepositReturnRoute: typeof InquiryDepositReturnRoute
}

const InquiryDepositRouteChildren: InquiryDepositRouteChildren = {
  InquiryDepositReturnRoute: InquiryDepositReturnRoute,
}

const InquiryDepositRouteWithChildren = InquiryDepositRoute._addFileChildren(
  InquiryDepositRouteChildren,
)

interface InquiryRouteChildren {
  InquiryDepositRoute: typeof InquiryDepositRouteWithChildren
}

const InquiryRouteChildren: InquiryRouteChildren = {
  InquiryDepositRoute: InquiryDepositRouteWithChildren,
}

const InquiryRouteWithChildren =
  InquiryRoute._addFileChildren(InquiryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  BuilderRoute: BuilderRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  DashboardRoute: DashboardRoute,
  InquiryRoute: InquiryRouteWithChildren,
  PreviewRoute: PreviewRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  StartRoute: StartRoute,
  SupportRoute: SupportRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
